version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=root
      - GITEA__database__PASSWD=root
    restart: always
    networks:
      - gitea
    volumes:
      - /Users/garlam/docker/gitea:/data   # - ./gitea:/data ./gitea = 当前文件夹下的gitea文件
      - /Users/garlam/docker/gitea/timezone:/etc/timezone:ro # 修改宿主机路径
      - /Users/garlam/docker/gitea/localtime:/etc/localtime:ro # 修改宿主机路径
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mysql-for-gitea
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_USER=garlam
      - MYSQL_DATABASE=gitea
      - MYSQL_LOG_CONSOLE=true
    ports:
      - 3306:3306
    networks:
        - gitea
    volumes:
      - /Users/garlam/docker/gitea/mysql:/var/lib/mysql
#      - /Users/garlam/docker/gitea/mysql/data:/var/lib/mysql
#      - /Users/garlam/docker/gitea/mysql/conf:/etc/mysql/conf.d
