# docker compose -f /Users/garlam/IdeaProjects/ace/docker-compose-ace-application.yml -p ace up -d
version: '3.8'

networks:
  ace-net: # 网络名
    name: ace-net
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16

services:

  application:
    build:
      context: .
      dockerfile: Dockerfile
    #    image: 87548744/ace:v3.2
    container_name: application
    hostname: application
    # restart: always
    volumes:
      #  - /Users/garlam/docker/ace/:/opt/workspace/ace/
      - C:\ace\:/opt/workspace/ace/
      - C:\Users\Garlam.Au\IdeaProjects\ace\target\ace-3.3.jar:/ace.jar #掛載jar, 重啟docker容器即可更新jar內容
    ports:
      - 8090:8090
    depends_on:
      - redis
      - mysql
      - rabbitmq
    networks:
      ace-net:
        ipv4_address: 172.25.0.10

  mysql:
    image: mysql:latest
    container_name: mysql-8
    restart: always
    hostname: mysql-8
    # platform: linux/x86_64
    environment:
      MYSQL_DATABASE: ace
      MYSQL_USER: garlam
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3310:3306
    networks:
      ace-net:
        ipv4_address: 172.25.0.11

  # for ace-application 开发环境使用
  mysql-dev:
    image: mysql:latest
    container_name: mysql-dev
    restart: always
    hostname: mysql-dev
    # platform: linux/x86_64
    environment:
      MYSQL_DATABASE: ace
      MYSQL_USER: garlam
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3388:3306
    networks:
      ace-net:
        ipv4_address: 172.25.0.100

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-3
    hostname: rabbitmq-3
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
      - 15674:15674
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      ace-net:
        ipv4_address: 172.25.0.12

  redis:
    image: redis:latest
    container_name: redis-7
    restart: always
    hostname: redis-7
    ports:
      - 6379:6379
    networks:
      ace-net:
        ipv4_address: 172.25.0.13

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    hostname: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: ace
    ports:
      - 27017:27017
    networks:
      ace-net:
        ipv4_address: 172.25.0.14



