version: '3.8'

networks:
  ace-net: # 网络名
    name: ace-net
    driver: bridge

services:

  application:
    build:
      context: .
      dockerfile: Dockerfile
    # image: ace-img:latest
    restart: always
    container_name: application
    ports:
      - 8090:8090
    depends_on:
      - redis
      - mysql
    networks:
      - ace-net

  mysql:
    image: mysql:latest
    container_name: mysql-8
    restart: always
    # platform: linux/x86_64
    environment:
      MYSQL_DATABASE: ace
      MYSQL_USER: garlam
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    networks:
      - ace-net

  redis:
    image: redis:latest
    container_name: redis-7
    restart: always
    ports:
      - 6379:6379
    networks:
      - ace-net





