CREATE OR REPLACE PACKAGE PKG_TEST AS
    TYPE X IS TABLE OF VARCHAR2(123);
    PROCEDURE XYZ(Y IN X);
END PKG_TEST;
/


CREATE OR REPLACE PACKAGE BODY PKG_TEST AS
    PROCEDURE XYZ(Y IN X) AS
    BEGIN
        FOR I IN Y.FIRST..Y.LAST
            LOOP
                DBMS_OUTPUT.PUT_LINE('THE VALUE OF I IS: ' || Y(I));
            END LOOP;
    END;

END PKG_TEST;
/


DECLARE

BEGIN
    PKG_TEST.XYZ(PKG_TEST.X('a','b','c','d','1','2','3'));
END;
/


DROP PACKAGE PKG_TEST;