@startuml
/'https://blog.csdn.net/hollis_chuang/article/details/120582502'/
title 货品检查流程图

actor User as user
participant "程序1,收货" as step_one
participant "程序2,查货" as step_two
participant "程序3,出货" as step_three
participant "程序4,装箱" as step_four


autonumber
user->step_one:收货拍照,上传货品照片和单号
activate step_one
step_one->step_two:输入单号,检查货品和照片相乎
activate step_two
step_two->step_three:输入单号,检查是否已检查
activate step_three
step_three->step_four:出货
deactivate step_two
step_two --> step_one:输入单号, 货品和照片对不上,退回收货
deactivate step_three
step_three --> step_two:输入单号, 货品未检查, 停止出货
deactivate step_one
step_one --> user:货不对版, 拒收
deactivate step_four



@enduml
